### ISSUE TITLE
release a new version

### ISSUE THREAD

**Issue by jspricke** [ros/diagnostics#106]
Hey Austin,

now with #99 in, can you please do a new release for kinetic and melodic?

Thanks a lot!

Jochen

**Comment by jspricke** [comment]
Note that #99 is actually a ABI break due to:

https://github.com/ros/diagnostics/pull/99/files#diff-27d11a6675817723f16ce5fad6c275f8R274

so not sure if we should rather wait for ROS N.

**Comment by mikepurvis** [comment]
I'm not an expert on ABI, but this change actually looks like it might be safe, reason being:

- There's no translation unit for `GenericAnalyzerBase`; the whole implementation is in the header, so any other implementations will be self-contained.
- The actual interface is the `Analyzer` class, which is unchanged, so an `Analyzer*` can safely point to instances of `GenericAnalyzerBase` implementations from before or after this change, and won't have any misalignment or even risks of, say calling a destructor with the wrong size.

I say release it into Melodic.

**Comment by jspricke** [comment]
I had a similar reasoning when I had a quick look, but debugged a nice segfault yesterday caused by it ;).

**Comment by mikepurvis** [comment]
Oh fun. Were you doing anything especially off-beat to cause that?

**Comment by jspricke** [comment]
We have an internal package on top of the aggregator using thelibdiagnostic_aggregator.so. Nothing special inside from first look.

**Comment by mikepurvis** [comment]
Does your internal code actually have pointers to instances of `GenericAnalyzerBase`, or only to instances of `Analyzer`?

**Comment by jspricke** [comment]
`Analyzer` and `GenericAnalyzer`.

**Comment by mikepurvis** [comment]
Okay, yeah I can see that being an issue then, since the size of `GenericAnalyzer` would have changed, and in particular, any fields in there would be offset from their previous locations.

Alas.

**Comment by Alabate** [comment]
In our case we are also interested in a new release on melodic because of #105 . We're trying to migrate our codebase to python3, and diagnostics are used across the whole project.

**Comment by flixr** [comment]
We also need #105 like @Alabate, if the whole thing can't be released as is, could the python3 fixes be backported instead?

**Comment by g-gemignani** [comment]
Does someone need also a new release for kinetic? Otherwise, I would close given https://github.com/ros/rosdistro/pull/26156 and https://github.com/ros/rosdistro/pull/26155
