### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by ryleymcc** [ros/diagnostics#178]
I'm getting an error saying that this is missing and i can't see it in my includes of my ROS2 directory. how should i install this?

**Comment by millerluki** [comment]
Which command did you use and what was the output? Which OS and ROS2 distro do you use?
Did you try this (for foxy)?
`sudo apt update`
`sudo apt install ros-foxy-diagnostic-updater`

**Comment by ryleymcc** [comment]
I changed my approach and am no longer using ros2.
