### ISSUE TITLE
ROS1 hd_monitor.py issue on noetic

### ISSUE THREAD

**Issue by chrisflesher** [ros/diagnostics#185]
Am getting the following error after running `hd_monitor.py` in noetic on Ubuntu 20.04 (pulling from latest apt):

```
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/diagnostic_common_diagnostics/hd_monitor.py", line 361, in <module>
    hostname_clean = string.translate(hostname, string.maketrans('-','_'))
AttributeError: module 'string' has no attribute 'translate'
```

**Comment by chrisflesher** [comment]
Also am getting the following error after running `sensors_monitor.py`:

```
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/diagnostic_common_diagnostics/sensors_monitor.py", line 46, in <module>
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO'
```

**Comment by g-gemignani** [comment]
Hi @chrisflesher and thank you for your message.
It looks like those nodes were never completely ported to python 3. I quickly did it. Can you please double-check that they are now working? You can find the fixes in https://github.com/ros/diagnostics/tree/noetic/fix-diagnostic-common-diagnostics
If it works for you I'll take care of creating a new release :)

**Comment by chrisflesher** [comment]
Thanks! I was able to get `hd_monitor.py` working after making the following fix:
```
diff --git a/diagnostic_common_diagnostics/src/diagnostic_common_diagnostics/sensors_monitor.py b/diagnostic_common_diagnostics/src/diagnostic_common_diagnostics/sensors_monitor.py
index e26fc8d..ffebb65 100755
--- a/diagnostic_common_diagnostics/src/diagnostic_common_diagnostics/sensors_monitor.py
+++ b/diagnostic_common_diagnostics/src/diagnostic_common_diagnostics/sensors_monitor.py
@@ -150,7 +150,7 @@ def _rpm_to_rads(rpm):
     return rpm * (2 * math.pi) / 60
 
 def parse_sensors_output(output):
-    out = StringIO(output)
+    out = StringIO(output.decode('utf-8'))
 
     sensorList = []
     for line in out.readlines():
```

I tried fixing `sensors_monitor.py` but found that code may need a significant rewrite for the `parse_sensor_line` function to be robust. Its crashing for multiple reasons with the following `sensors` output:
```
BAT0-acpi-0
Adapter: ACPI interface
in0:          10.00 V  
```

**Comment by chrisflesher** [comment]
I think I'd be pretty happy with the fix for `hd_monitor.py` now.

Maybe we could try to fix `sensors_monitor.py` as a separate issue? Would setting up some unit tests be helpful? I wouldn't mind taking a crack at that if I get some time to work on it.

**Comment by chrisflesher** [comment]
The sensors issue seems like a duplicate of #69

**Comment by g-gemignani** [comment]
Hi @chrisflesher, you are right, there was still an issue with sensors_monitor.py. Can you try now?

**Comment by chrisflesher** [comment]
Yes `sensors_monitor.py` seems to run now. Thanks!

**Comment by chrisflesher** [comment]
A new release of this would be great. I have only tested it on a VM, could test on actual hardware next week and report results if that would be helpful.

**Comment by g-gemignani** [comment]
We are in no rush. Let's wait for your additional test and then I take care of merging and releasing. Thank you!

**Comment by g-gemignani** [comment]
@chrisflesher any update on this?

**Comment by g-gemignani** [comment]
Merged to noetic-devel. Closing the issue
