### ISSUE TITLE
How can I add a new group analyzer as a plugin?

### ISSUE THREAD

**Issue by KeisukeShima** [ros/diagnostics#213]
HI,
I am developing a plugin for `diagnostic_aggregator`. This will be a replacement for the existing `AnalyzerGroup`, but with different behavior.
However, my group plugin does not hierarchize correctly because `AnalyzerGroup` only recognizes `diagnostic_aggregator/AnalyzerGroup` as a group in the following line.

https://github.com/ros/diagnostics/blob/ros2-devel/diagnostic_aggregator/src/analyzer_group.cpp#L148

Since the root `AnalyzerGroup` is hard-coded `diagnostic_aggregator/AnalyzerGroup`, I have no way to avoid this.
Once the group plugins are working correctly, users will be free to create their own plugins. This would be great!
I think it will only take a few changes to fix this problem. I would be happy to help.

https://github.com/ros/diagnostics/blob/ros2-devel/diagnostic_aggregator/include/diagnostic_aggregator/aggregator.hpp#L150

**Comment by ct2034** [comment]
Fixed in #221
