### ISSUE TITLE
Why "FrequencyStatusParam" receive pointers?

### ISSUE THREAD

**Issue by doronhi** [ros/diagnostics#225]
Why does FrequencyStatusParam receive pointers and not variables?
From a user perspective, it is cumbersome. I need to keep 2 variables, min_freq, max_freq during the whole run of the program.
It would be much cleaner, to initialize with `FrequencyStatusParam(0.9*expected_freq, 1.1*epected_freq)`.
What is the benefit of passing these values as pointers?

**Comment by ct2034** [comment]
Hi @doronhi.
Thanks for your very good question. :smiley: 
I think the ideas is for you to be able to update the frequencies later. Please feel free to open a PR with an overloaded constructor that takes values. 
I case this did not answer your question, please reopen the issue.
