### ISSUE TITLE
[ros2] The latest commits in ros2 branch have not been released to rolling/humble distribution.

### ISSUE THREAD

**Issue by wep21** [ros/diagnostics#229]
The latest release version is 2.1.3, but the latest ros2 branch goes a bit ahead.

**Comment by wep21** [comment]
@Karsten1987 @norro Could you create a new release to rolling/humble?

**Comment by wep21** [comment]
@g-gemignani Hi, I guess you are in charge of ros1 branch maintenance. Currently, the maintainer of ros2 branch (@Karsten1987 @norro) seems to be inactive. Is it possible for me to do release process instead of them until they are back?

**Comment by wep21** [comment]
cc @clalancette

**Comment by clalancette** [comment]
I'm not a maintainer here, so I'm reluctant to add people as maintainers without agreement from the current maintainers.

That said, I'm happy to do a release here, so I'll go ahead and do that.

**Comment by clalancette** [comment]
Done in https://github.com/ros/rosdistro/pull/33526 and https://github.com/ros/rosdistro/pull/33527

**Comment by wep21** [comment]
@clalancette Thank you for taking care of it!
