### ISSUE TITLE
ROS2 Missing ament_export_target in diagnostic_aggregation CMake 

### ISSUE THREAD

**Issue by AzaelCicero** [ros/diagnostics#236]
I am writing my own plugin for the diagnostic and I needed to call `StatusItem::toStatusMsg` https://github.com/ros/diagnostics/blob/galactic/diagnostic_aggregator/include/diagnostic_aggregator/status_item.hpp#L222-L224 

I was getting a linking error:

> /usr/bin/ld: libas_monitor_analyzers_lib.so: undefined reference to `diagnostic_aggregator::StatusItem::toStatusMsg(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) const'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/as_monitor_analyzers_test.dir/build.make:210: as_monitor_analyzers_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:125: CMakeFiles/as_monitor_analyzers_test.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

The issue is that CMake does not export the diagnostic_aggregator library:  https://github.com/ros/diagnostics/blob/galactic/diagnostic_aggregator/CMakeLists.txt#L158-L164

It should look like this:
```
ament_export_targets(${PROJECT_NAME} HAS_LIBRARY_TARGET)
ament_export_libraries(${PROJECT_NAME})
```

Is it by design?

**Comment by RFRIEDM-Trimble** [comment]
This [PR](https://github.com/ros/diagnostics/pull/240/files#diff-9b32c4fea3562a42e90c9950a63b48b8fe78a531f5cbd87b1bff457920c8b781R159) added that line for `ament_export_targets`. `ament_export_libraries` is not needed if you use ament_export_targets according to [this](https://github.com/ament/ament_cmake/issues/365). 

I think this issue can be closed.

**Comment by ct2034** [comment]
I agree. I think we can close this
