### ISSUE TITLE
Deprecate ntpdate usage, replace with ntpd in NTP Monitor

### ISSUE THREAD

**Issue by RFRIEDM-Trimble** [ros/diagnostics#253]
https://linux.die.net/man/8/ntpdate

The NTP Monitor used ntpdate to get the time offsets for NTP, however that package will be deprecated in the future. Since rosdep already has a key for `ntpd`, the following needs to change
* Change rosdep key 
* Adjust the CLI call to use ntpd
* Change any command line arguments as needed for the [ntpd](https://linux.die.net/man/8/ntpd) call

It is available in ubuntu 22.04 currently (humble); I have yet to find the specific release it will not be available. Just filing this issue to keep tabs on it.

**Comment by ct2034** [comment]
Hey @RFRIEDM-Trimble. How do you know ntpdate will be deprecated. It seems to be supported so far: https://packages.ubuntu.com/search?keywords=ntpdate
On the other hand: there is no rosep key for `ntpd` but there is one for `ntp`. But I was not able to find a way we could achieve a similar behavior to the current with the tools in `ntp`.
Another package I found that  would work is `sntp`. 

The other issue is rhel: Is there anyone who knows a tool to query a ntp server in rhel? I did not find one that does what we need.
