### ISSUE TITLE
Add tests for NTP Monitor

### ISSUE THREAD

**Issue by RFRIEDM-Trimble** [ros/diagnostics#254]
The NTP monitor is now ported to ROS2, but there are no tests for it.Proposed issue scope:

- [ ] Add dependency on pytest such that tests run with colcon
- [ ] Add a new python file for testing the ntp monitor
- [ ] Add a test for parsing the output of ntpdate
- [ ] Add a test for ensuring the offset threshold results in levels 0,1,2 of diagnostic status
- [ ] Any other test suggestions are welcome

 I can take assignment of this ticket and issue a PR for it.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/what-is-the-recommended-pytest-workflow-for-an-ament-cmake-python-package/28471/1

**Comment by ct2034** [comment]
see #255
