### ISSUE TITLE
diagnostic_aggregator: catkin_make -DCATKIN_ENABLE_TESTING=0 fails

### ISSUE THREAD

**Issue by bulwahn** [ros/diagnostics#27]
When executing `catkin_make -DCATKIN_ENABLE_TESTING=0`, it fails with:

Linking CXX executable (...)/diagnostics_ws/devel/lib/diagnostic_aggregator/analyzer_loader
/usr/bin/ld: cannot find -lgtest
collect2: error: ld returned 1 exit status
make[2]: *** [(...)/diagnostics_ws/devel/lib/diagnostic_aggregator/analyzer_loader] Error 1

diagnostic_aggregator in version 1.8.4 needs the gtest library, but this is only discovered for linking when testing is enabled in catkin.

**Comment by trainman419** [comment]
Closing due to lack of response from @bulwahn
