### ISSUE TITLE
Use Diagnostics aggregator node with other topic names

### ISSUE THREAD

**Issue by rebeccaRossRobotics** [ros/diagnostics#300]
Hi!

I have multiple topics which have a msg type of `diagnostic_msgs/msg/DiagnosticArray`. Is there a way to get the diagnostics_aggregator node to listen to them?

I have tried to remap one back to be on the `/diagnostics` topic but nothing is piping back to `/diagnostics`. Here is the code I have for starting the aggregator node and remapping.
```
diagnostic_aggregator_node = Node(
        package='diagnostic_aggregator',
        executable='aggregator_node',
        remappings=[("/diagnostics_cyphal", "/diagnostics")],
        parameters=[diagnostic_aggregator_config_file],
    )
```

Thanks!

**Comment by ct2034** [comment]
All diagnostics messages should be published in the `\diagnostics` topic. Otherwise, the remapping strategy would be also my best bet. But I have never worked with topic remapping in ROS2, so I can not help you there.
