### ISSUE TITLE
[Feature request] Add new aggregation rule to diagnostic_aggregator

### ISSUE THREAD

**Issue by garaemon** [ros/diagnostics#31]
diagnostic_aggregator initialize analyzers from rosparam and it cannot add new analyzing rule after initialization. If it supports addition of rules, it would be very useful.

It means that if we want to add new rule, we need to run another aggregator and robot_monitor with remapping like `/diagnostics -> /diagnostics_perception`.

**Comment by trainman419** [comment]
I don't think an add/delete API on a per-item basis is really appropriate for the way that this should be used; it gives the user too much freedom to accidentally remove important diagnostics.

The nominal use-case that I see for this API would be wanting to bring up additional diagnostics as part of a capability, and bring those diagnostics down again when that capability is no longer needed.

Perhaps something based on a model like `bond` would be more appropriate?

**Comment by guillaumeautran** [comment]
Has there be any progress made on this feature request? 
I am (selfishly) volunteering myself to do the grunt work here if we could come up with a agreement on the API.

**Comment by guillaumeautran** [comment]
Would specifying an `analyzers.yaml` file in the `package.xml` `<export/>` tag be a possible avenue? When the node comes up, the diagnostic aggregator could dynamically load the new YAML file and update its configuration. 
There would not be any unload capability though...

**Comment by trainman419** [comment]
This has been implemented in #43
