### ISSUE TITLE
About the use of this diagnostic node package

### ISSUE THREAD

**Issue by TZECHIN6** [ros/diagnostics#314]
It seems this package focuses on hardware-level diagnostic, is it able to monitor the state of a node?

It is very common that a ROS project includes numbers of node, I am finding a way to check the status of node, and publish an error or warning when any of operational nodes is down.

I am very new to this package, and not sure will this overkill my purpose.

**Comment by ct2034** [comment]
Hi @TZECHIN6. I agree that this may be a common use case. Currently, there is no pre-made node for that. Please feel free to add one to: https://github.com/ros/diagnostics/tree/ros2/diagnostic_common_diagnostics :)

**Comment by TZECHIN6** [comment]
To verify a node is dead or not, what is the best way to do so, a very simple method is to publish a heartbeat message say every single second, but this come to creating a whole bunch of messages if there are many nodes.

is there any build in function in ros2 can directly access its state? 

get_node_names() Function in rclpy will list out all node within ROS2 environment, I am not sure does a node can be seen mean that node is alive and functioning…

**Comment by ct2034** [comment]
Yes, the `get_node_names()` (https://docs.ros2.org/galactic/api/rclpy/api/node.html#rclpy.node.Node.get_node_names) method should return all running nodes. I am not sure, though, how quickly a node is removed after it dies. Maybe you have to test this.

**Comment by TZECHIN6** [comment]
I can come up with a very quick way to test it using python list element check, but this come down to hardcoding the node name needed to be checked... which some time the launch file can rename the node. So I am not so sure is there any dynamic way to solve this if using `get_node_names()`.

I can share it to the common diagnostics, do you expect the output of the diagnostics result in a form of this `/diagnostic` topic? Acutally I havent use this before, so have to understand the structure of it..

**Comment by ct2034** [comment]
You can publish the results similar to how it is done here https://github.com/ros/diagnostics/blob/ros2/diagnostic_updater/diagnostic_updater/example.py

**Comment by TZECHIN6** [comment]
I just spotted that there is a class ([here](https://github.com/ros/diagnostics/blob/ros2/diagnostic_updater/diagnostic_updater/_update_functions.py#L255C1-L269C20)) actually doing something to what i want, check a node is alive or not. but I am not so sure how to use it. I will rise another issue about that. Thanks
