### ISSUE TITLE
How to implement heartbeat diagnostic in ros2 system

### ISSUE THREAD

**Issue by TZECHIN6** [ros/diagnostics#316]
I would like to check whether each node on my system is alive or not, and I found there is a class Heartbeat that seems to be doing this. I am not so familiarised with classes and, thus have no idea where to start with.

Say under the ros2 workspace, there are two nodes, minimal publisher node and minimal subscribe node. How can I implement this heartbeat diagnostic into this system? Also, how does it know which node name to find for?

Any guidance is appreciated.

**Comment by ct2034** [comment]
The [Hearbeat](https://github.com/ros/diagnostics/blob/0af0de12889f748cf9b29591a1a365ad5ac9eb82/diagnostic_updater/diagnostic_updater/_update_functions.py#L255C7-L255C16) is a diagnostics task like others. So you can add it to an updater:
```python
node = rclpy.create_node('node_with_heartbeat')
heartbeat = Heartbeat()
updater = Updater(node)
updater.setHardwareID('node_with_heartbeat')
updater.add(heartbeat)
```
It will then publish OK as long as the updater is updated, and the node is active. For it to become useful, you also need an aggregator that will [switch to the stale state](https://github.com/ros/diagnostics/blob/0af0de12889f748cf9b29591a1a365ad5ac9eb82/diagnostic_aggregator/README.md?plain=1#L120) in case the heartbeat did not occur for 5s.

Feel free to reopen if you have further questions.
