### ISSUE TITLE
diagnostics_common_diagnostics doesn't build on OSX

### ISSUE THREAD

**Issue by trainman419** [ros/diagnostics#36]
As seen on ROS answers: http://answers.ros.org/question/199874/no-definition-of-libsensors4-dev-for-os-osx/

Doesn't build on OSX because libsensors4-dev isn't available on OSX.

@mitchellwills thoughts on how to fix this? It's easy enough to make the build process skip the libsensors node if libsensors isn't available, but we'd still have to figure out how to specify the dependency properly, because ROS doesn't support the notion of system-specific or optional dependencies.

Thoughts?

**Comment by trainman419** [comment]
I haven't come up with anything better. I think we should move the new, linux-specific diagnostics into a separate package.

**Comment by mitchellwills** [comment]
Would you like me do submit a PR for this in this repo or should I try to move it into the linux_peripheral_interfaces repo?

**Comment by garaemon** [comment]
Is this kind of patch enough?
https://github.com/garaemon/diagnostics/compare/gtest-1.7.0-for-self-test...do-not-compile-sensors-on-os-x

**Comment by trainman419** [comment]
Sorry for the slow responses; I've been on vacation and I'm a bit busy moving to a new apartment.

@garaemon that isn't sufficient, because it still leaves the dependency on libsensors in the package.xml

@mitchellwills why don't you submit the current version of the libsensors node to the linux_peripheral_interfaces repo. I'll keep the existing node in a branch of this repository or something and try to do an updated release in the next few days.

**Comment by garaemon** [comment]
> @garaemon that isn't sufficient, because it still leaves the dependency on libsensors in the package.xml

Exactly.

**Comment by mitchellwills** [comment]
@trainman419 Might want to soon as I think there is going to be another sync soon

**Comment by trainman419** [comment]
I've removed the libsensors node from the hydro-devel branch. Please try that.

**Comment by trainman419** [comment]
Released into Hydro and Indigo as version 1.8.7
