### ISSUE TITLE
common_diagnostics CPU monitoring fails on hostname with added domain

### ISSUE THREAD

**Issue by sjusner** [ros/diagnostics#404]
The hostname generated by `socket.gethostname()` can contain non-alphanumeric symbols, e.g. when a domain is added: hostname.domain.com
Currently, the cpu, ram and sensor monitoring fail due to incomplete string sanitation.

Solution: 
Better string sanitation for all common_diagnostics nodes (also adds more consistent behavior)

**Comment by ct2034** [comment]
Thanks for reporting the bug. I will look into this
