### ISSUE TITLE
ros-kinetic-diagnostics-aggregator deb missing from xenial 16.04 on shadow-fixed

### ISSUE THREAD

**Issue by UltronDestroyer** [ros/diagnostics#64]
I'm running some pre-release tests and noticed it is missing for some reason.

http://packages.ros.org/ros-shadow-fixed/ubuntu/pool/main/r/ros-kinetic-diagnostic-aggregator/

specifically,

amd64.deb for xenial

**Comment by tfoote** [comment]
This was a recurrence of https://github.com/ros-infrastructure/ros_buildfarm/pull/377 I've manually fixed the package and it's rebuilding downstream now. http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__diagnostic_aggregator__ubuntu_xenial_amd64__binary/

**Comment by UltronDestroyer** [comment]
Thanks Tully. Ill keep an eye on other occurences

**Comment by trainman419** [comment]
I've confirmed that the diagnostics debs are present in shadow-fixed again. Closing.
