### ISSUE TITLE
Travis build fails since ca. 2 months

### ISSUE THREAD

**Issue by LoyVanBeek** [ros/diagnostics#74]
For the Travis build of this repo, they currently seem to fail on 
```python
ImportError: "from catkin_pkg.package import parse_package" failed: No module named catkin_pkg.package
```
This Python package is in the python-catkin-pkg, which is a dependency of python-catkin, which is [installed](https://github.com/ros/diagnostics/blob/indigo-devel/.travis.yml#L14) in the .travis-file. 

Currently there are 2 PRs failing on that error:
- https://github.com/ros/diagnostics/pull/72 fails at https://travis-ci.org/ros/diagnostics/builds/335289179#L2299
- https://github.com/ros/diagnostics/pull/73 fails at https://travis-ci.org/ros/diagnostics/builds/336956455#L2162 (mine, which triggered me to check out other PRs as well). 

Another recent PR does not fail on this error but fails already earlier: https://github.com/ros/diagnostics/pull/70

**Comment by trainman419** [comment]
Fixed in #76
