### ISSUE TITLE
Release into melodic

### ISSUE THREAD

**Issue by clalancette** [ros/diagnostics#81]
It looks like all of the dependencies for `diagnostics` are available in Melodic, so it would be great to get this released.  Thanks in advance!

**Comment by ayrton04** [comment]
+1

**Comment by kmhallen** [comment]
+1

**Comment by clalancette** [comment]
Ping?  Could we get this released into Melodic, please?  Thank you.

**Comment by trainman419** [comment]
Sorry for the delay. Released: https://github.com/ros/rosdistro/pull/17713
