### ISSUE TITLE
Division by zero if time does not change between updates

### ISSUE THREAD

**Issue by poggenhans** [ros/diagnostics#92]
To determine the update frequency, the diagnostic_updater divides by the time since the last update here: https://github.com/ros/diagnostics/blob/indigo-devel/diagnostic_updater/include/diagnostic_updater/update_functions.h#L174

If the time has not changed since then (happend to me when playing a rosback with `use_sim_time`), we divide by zero.

**Comment by wkhudgins92** [comment]
What would the desired behavior be here? I'm not sure that returning any numerical value would be truthful. Perhaps outputting N/A on line 199?

**Comment by poggenhans** [comment]
I would simply not add the frequency to the status message if `window` is zero.

**Comment by wkhudgins92** [comment]
Valid idea. I'll implement something and raise a PR for this...thanks @poggenhans
